### ISSUE TITLE
Add package to Conda

### ISSUE THREAD

**Issue by mikeheddes** [hyperdimensional-computing/torchhd#36]
We would like to make the package available on Conda under torchhd. I need some help from someone experienced with setting that up because I have not managed so far.

**Comment by fabhertz95** [comment]
Hi! I suggest to look up [Tonic](https://github.com/neuromorphs/tonic). They (or we, since I am a collaborator) implemented an automatized way to push to conda-forge the code everytime a new release is created. In particular, [here](https://github.com/conda-forge/tonic-feedstock) the push is automatized upon release creation.

P.S. Thank you for your amazing work. I was tired or designing my own PyTorch code for my HDC research :)

**Comment by fabhertz95** [comment]
Hi! I am not able to find the package on conda. I also looked up the conda-forge channel, without success. Could you help me?

P.S. Thank you for the amazing work. I was tired of designing my own code from NumPy and PyTorch for my research :)

**Comment by mikeheddes** [comment]
Hi @fabhertz95 thanks for your comment! We are actively resolving an issue we had with our Conda package. I hope it will be working later today or early next week. Do you happen to have experience publishing to Conda? If so maybe you could help us. For now the library is available on PyPi. I will update this issue if I have more info.

**Comment by fabhertz95** [comment]
Hi @mikeheddes! No, I do not have that kind of experience. However, I am a collaborator on another repository, where they have automatized the conda-orge push at every release creation. [This](https://github.com/conda-forge/tonic-feedstock) is the link. I hope it helps :)

**Comment by mikeheddes** [comment]
I think I got it to work with Conda, you can now install the library also using `conda install -c torchhd torchhd` since version 2.2.2. Let me know if you are experiencing any issues.
